[package]
name = "matmul"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-cpuid = "11.2.0"
rayon = "1.10.0"

[[bench]]
name = "matmul"
harness = false

[dev-dependencies]
criterion = "0.5.1"
faer = "0.20.1"
gemm = "0.18.0"
rand = "0.8.5"
